import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-900">
        <h1 className="text-2xl text-slate-200">Welcome to Prisma Schema Generator</h1>
        <button className="">
          <Link href="/schema">
            Create a Schema
          </Link>
        </button>
      </main>
    </>
  );
};

export default Home;

